@echo off
REM === MSIX Packaging Script for vram-monitor ===
REM Generated by tauri-msix. Re-run anytime to rebuild the .msix.

REM --- Cd to project root (this script lives in scripts/) ---
cd /d "%~dp0.."

REM --- Check and install WinApp CLI ---
where winapp >nul 2>&1
if %errorlevel% neq 0 (
    echo winapp command not found. Installing Microsoft.WinAppCli...
    winget install Microsoft.WinAppCli --accept-source-agreements --accept-package-agreements
)

REM --- Build if exe missing ---
if not exist .\src-tauri\target\release\vram-monitor.exe (
    echo Executable not found. Running build...
    npm run tauri build
)

REM --- Generate and install dev cert if missing ---
if not exist devcert.pfx (
    echo Certificate not found. Generating and installing...
    winapp cert generate
    sudo winapp cert install .\devcert.pfx
)

REM --- Prepare pack directory ---
if exist msix rmdir /s /q msix
mkdir msix

REM --- Copy files ---
copy .\src-tauri\target\release\vram-monitor.exe .\msix
copy .\appxmanifest.xml .\msix
xcopy /E /I .\icons .\msix\icons
copy /Y .\src-tauri\icons\icon.ico .\msix\icons\icon.ico 2>nul

REM --- Sanitize manifest: MSIX forbids hyphens in Identity Name / Application Id ---
powershell -NoProfile -Command "(Get-Content -LiteralPath '.\msix\appxmanifest.xml' -Raw) -replace '<Identity\s+Name=\"vram-monitor\"', '<Identity Name=\"vrammonitor\"' -replace '<Application\s+Id=\"vram-monitor\"', '<Application Id=\"vrammonitor\"' | Set-Content -LiteralPath '.\msix\appxmanifest.xml' -NoNewline"

REM --- Pack and sign ---
winapp pack .\msix --cert .\devcert.pfx

REM --- Cleanup ---
rmdir /s /q .\msix

echo === MSIX packaging completed ===
